//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.18020.
// 
namespace Enterprise.Services.WebServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataSetServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DataSetService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOverdueRecoveringOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAvaliableBooksOperationCompleted;
        
        /// <remarks/>
        public DataSetService() {
            this.Url = "http://localhost/Enterprise.Web/DataSetService.asmx";
        }
        
        /// <remarks/>
        public event GetOverdueRecoveringOrdersCompletedEventHandler GetOverdueRecoveringOrdersCompleted;
        
        /// <remarks/>
        public event GetAvaliableBooksCompletedEventHandler GetAvaliableBooksCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOverdueRecoveringOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOverdueRecoveringOrders() {
            object[] results = this.Invoke("GetOverdueRecoveringOrders", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOverdueRecoveringOrders(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOverdueRecoveringOrders", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetOverdueRecoveringOrders(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetOverdueRecoveringOrdersAsync() {
            this.GetOverdueRecoveringOrdersAsync(null);
        }
        
        /// <remarks/>
        public void GetOverdueRecoveringOrdersAsync(object userState) {
            if ((this.GetOverdueRecoveringOrdersOperationCompleted == null)) {
                this.GetOverdueRecoveringOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOverdueRecoveringOrdersOperationCompleted);
            }
            this.InvokeAsync("GetOverdueRecoveringOrders", new object[0], this.GetOverdueRecoveringOrdersOperationCompleted, userState);
        }
        
        private void OnGetOverdueRecoveringOrdersOperationCompleted(object arg) {
            if ((this.GetOverdueRecoveringOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOverdueRecoveringOrdersCompleted(this, new GetOverdueRecoveringOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAvaliableBooks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAvaliableBooks() {
            object[] results = this.Invoke("GetAvaliableBooks", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAvaliableBooks(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAvaliableBooks", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetAvaliableBooks(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAvaliableBooksAsync() {
            this.GetAvaliableBooksAsync(null);
        }
        
        /// <remarks/>
        public void GetAvaliableBooksAsync(object userState) {
            if ((this.GetAvaliableBooksOperationCompleted == null)) {
                this.GetAvaliableBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvaliableBooksOperationCompleted);
            }
            this.InvokeAsync("GetAvaliableBooks", new object[0], this.GetAvaliableBooksOperationCompleted, userState);
        }
        
        private void OnGetAvaliableBooksOperationCompleted(object arg) {
            if ((this.GetAvaliableBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvaliableBooksCompleted(this, new GetAvaliableBooksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    public delegate void GetOverdueRecoveringOrdersCompletedEventHandler(object sender, GetOverdueRecoveringOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOverdueRecoveringOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOverdueRecoveringOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    public delegate void GetAvaliableBooksCompletedEventHandler(object sender, GetAvaliableBooksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvaliableBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvaliableBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}
