
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'ThomsonReuters');
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'RELX');
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'Wolters Kluwer');
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'Penguin Random House');
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'Hachette Livre');
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'Holtzbrinck');
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'Grupo Planeta');
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'Scholastic');
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'Wiley');
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'Informa');
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'Shogakukan');
insert into publishers (id, publisher_title) values(seq_publishers.nextval, 'Bonnier');

insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Fedor','Dostoevskii`');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Lev','Tolstoi`');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Mihail','Bulgakov');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Nicolai`','Gogol`');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Alexander','Pushkin');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Anton','Chehov');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Ivan','Turgenev');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'E`rnest','KHemingue`i`');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Victor','Giugo');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Alexander','Diuma');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Uil`iam','Shekspir');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Mihail','Lermontov');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Mark','Tven');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Zhiul`','Vern');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'George','Orue`ll');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Alexander','Griboedov');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Jack','London');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Ivan','Goncharov');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Aleksei`','Tolstoi`');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Mihail','Sholohov');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Stanislaus','Lem');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Lewis','Ke`rroll');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Charles','Dikkens');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Ivan','Efremov');
insert into authors (id, firstName, lastName) values(seq_authors.nextval, 'Oscar','Uai`l`d');

insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'In Search of Lost Time by Marcel Proust', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Ulysses by James Joyce', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Don Quixote by Miguel de Cervantes', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Moby Dick by Herman Melville', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Hamlet by William Shakespeare', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'War and Peace by Leo Tolstoy', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'War and Peace by Leo Tolstoy', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Odyssey by Homer', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Great Gatsby by F. Scott Fitzgerald', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Divine Comedy by Dante Alighieri', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Madame Bovary by Gustave Flaubert', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Brothers Karamazov by Fyodor Dostoyevsky', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'One Hundred Years of Solitude by Gabriel Marquez', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Adventures of Huckleberry Finn by Mark Twain', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Iliad by Homer', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Lolita by Vladimir Nabokov', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Anna Karenina by Leo Tolstoy', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Crime and Punishment by Fyodor Dostoyevsky', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Alices Adventures in Wonderland by Lewis Carroll', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Sound and the Fury by William Faulkner', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Pride and Prejudice by Jane Austen', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Catcher in the Rye by J. D. Salinger', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Wuthering Heights by Emily Brontë', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Nineteen Eighty Four by George Orwell', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Heart of Darkness by Joseph Conrad', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'To the Lighthouse by Virginia Woolf', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Absalom, Absalom! by William Faulkner', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Middlemarch by George Eliot', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Trial by Franz Kafka', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'One Thousand and One Nights by India/Iran/Egypt', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Stories of Anton Chekhov by Anton Chekhov', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Red and the Black by Stendhal', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Gullivers Travels by Jonathan Swift', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Catch-22 by Joseph Heller', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2),  round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Grapes of Wrath by John Steinbeck', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Invisible Man by Ralph Ellison', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Stranger by Albert Camus', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Great Expectations by Charles Dickens', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Aeneid by Virgil', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'David Copperfield by Charles Dickens', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Mrs. Dalloway by Virginia Woolf', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Beloved by Toni Morrison', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Canterbury Tales by Geoffrey Chaucer', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Collected Fiction by Jorge Luis Borges', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Leaves of Grass by Walt Whitman', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Candide by Voltaire', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Jane Eyre by Charlotte Brontë', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'As I Lay Dying by William Faulkner', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Sun Also Rises by Ernest Hemingway', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'The Complete Stories of Franz Kafka by Franz Kafka', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));
insert into books (id, description, isbn, penalty_price, publisher_id) values(seq_books.nextval, 'Tristram Shandy by Laurence Sterne', round(dbms_random.value(30,2020)), round(dbms_random.value(1,200), 2), round(dbms_random.value(1,13)));

insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 1, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 2, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 3, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 4, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 5, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 6, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 7, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 8, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 9, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 10, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 11, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 12, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 13, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 14, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 15, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 16, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 17, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 18, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 19, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 20, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 21, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 22, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 23, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 24, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 25, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 26, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 27, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 28, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 29, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 30, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 31, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 32, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 33, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 34, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 35, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 36, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 37, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 38, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 39, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 40, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 41, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 42, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 43, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 44, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 45, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 46, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 47, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 48, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 49, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 50, round(dbms_random.value(30,2020)));
insert into inventoryitems(id, is_ordered, is_readcarted, book_id, inventory_code) values(seq_inventoryitems.nextval, 0, 0, 51, round(dbms_random.value(30,2020)));


insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 1, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 2, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 3, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 4, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 5, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 6, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 7, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 8, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 9, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 10, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 11, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 12, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 13, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 14, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 15, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 16, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 17, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 18, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 19, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 20, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 21, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 22, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 23, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 24, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 25, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 26, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 27, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 28, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 29, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 30, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 31, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 32, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 33, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 34, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 35, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 36, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 37, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 38, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 39, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 40, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 41, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 42, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 43, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 44, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 45, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 46, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 47, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 48, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 49, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 50, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 51, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 1, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 2, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 3, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 4, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 5, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 6, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 7, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 8, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 9, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 10, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 11, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 12, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 13, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 14, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 15, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 16, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 17, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 18, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 19, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 20, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 21, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 22, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 23, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 24, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 25, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 26, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 27, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 28, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 29, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 30, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 31, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 32, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 33, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 34, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 35, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 36, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 37, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 38, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 39, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 40, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 41, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 42, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 43, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 44, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 45, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 46, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 47, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 48, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 49, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 50, round(dbms_random.value(1, (select count(id) from authors ))));
insert into books_to_authors (id, book_id, author_id) values (seq_books_to_authors.nextval, 51, round(dbms_random.value(1, (select count(id) from authors ))));


insert into reader (reader_id, email_address) values(seq_reader.nextval, 'DanilinaPaulina@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'KolmakovaAnna@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'Zhigul`skaiaIrina@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'TereshkovSergey@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'LeepovikMaksim@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'Chui`kovIaroslav@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'Bobry`shovAndrei@gmail.com`');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'MinzhukovAleksei@gmail.com`');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'GololobovDmitrii@gmail.com`');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'NicolaevVladislav@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'TamanaevaMaria@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'BondarenkoAlexander@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'ZhuravlevVictor@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'Sokol`tcovDmitrii`@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'Dobetckii`Konstantin@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'GanievFanis@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'MiasnikovAnton@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'KaaVictor@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'NazarovDenis@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'CheremisinVadim@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'TanaevAlexander@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'DorozhkoAnton@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'RomanKarpov@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'KurziakovArtyom@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'KHriukovAlexander@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'KiselevVladimir@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'ZlokazovDmitrii`@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'Iurii`Nikitin@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'KalaginAlexander@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'KostiuchenkoRoman@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'EgorovSergey@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'Skry`pnikovEvgenii`@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'Sal`nikovKonstantin@gmail.com');
insert into reader (reader_id, email_address) values(seq_reader.nextval, 'BukvinAleksei`@gmail.com');

insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 1); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 2); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 3); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 4); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 5); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 6); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 7); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 8); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 9); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 10); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 11); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 12);
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 13); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 14); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 15); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 16); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 17); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 18); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 19); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 20); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 21); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 22); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 23); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 24); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 25); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 26); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 27); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 28);
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 29); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 30); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 31); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 32); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 33); 
insert into readercart (id, cart_number, reader_id) values (seq_reader_cart.nextval,round(dbms_random.value(30,2020)), 34); 


